/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catching;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javazoom.jlgui.basicplayer.BasicPlayer;
import javazoom.jlgui.basicplayer.BasicPlayerException;

/**
 *
 * @author Dulce
 */
public class Juego extends javax.swing.JFrame implements KeyListener{

    /**
     * Creates new form Juego
     */
    
    HiloComida h1;
    
    private Random i = new Random();
    private int im =  (int)(i.nextDouble() * 8 + 1);
    public static int puntos = 0;
    public static int vidas = 3;
    BasicPlayer sonido;
    String archivo ="C:\\Users\\Dulce\\Documents\\NetBeansProjects\\Catching\\src\\sonido\\NIVEL1.mp3";
    //int puntosT;
    
    public Juego() {
        setTitle("NIVEL 1");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/manzana.png"));
        setIconImage(icon);
        initComponents();
        comida1.setVisible(false);
        btn_pausa.setEnabled(false);
        btn_reiniciar.setEnabled(false);
    }
    
    public void iniciarTeclas()
    {
        imgrandom();
        comida1.setVisible(true);
        chango.requestFocus();
        chango.addKeyListener(this);
        h1 = new HiloComida(comida1, chango, etq_puntos, etq_vidas);
        h1.start();
        
        
    }
    
    public void iniciarSonido()
    {
        try
        {
            sonido = new BasicPlayer();
            sonido.open(new File(archivo));
            sonido.play();
        }
        catch(BasicPlayerException ex)
        {
            System.out.println("Error iniciar sonido" + ex);
        }
    }
    
    public void detenerSonido()
    {
        try
        {
            sonido.open(new File(archivo));
            sonido.stop();
            
        }
        catch(BasicPlayerException ex)
        {
            
        }
    }
    
    public void pauseSonido()
    {
        try {
            sonido.pause();
        } catch (BasicPlayerException ex) {
            System.out.println("Error al pausar sonido" + ex);
        }
    }
    
    public void reanudarSonido()
    {
        try {
            sonido.resume();
        } catch (BasicPlayerException ex) {
            System.out.println("Error al reaundar sonido" + ex);
        }
    }
    
    
   public void imgrandom()
    {
        
        if(im == 1 || im == 5)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/coco.png")).getImage()));
        }
        else if(im == 2 || im == 6)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/platano.png")).getImage()));
        }
        if(im == 3 || im == 7)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/manzana.png")).getImage()));
        }
        if(im == 4 || im == 8)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/pera.png")).getImage()));
        }
        
    }
    
    public void iniciar()
    {
        iniciarTeclas();
        btn_pausa.setEnabled(true);
        btn_iniciar.setEnabled(false);
        if(puntos == 3)
        {
            h1.stop();
            h1 = null;
            puntos = 0;
            detenerSonido();
            this.dispose();
            CambioNivel2 cn2 = new CambioNivel2();
            cn2.setBounds(30,30,400,335);//setBounds(10, 10, 600,500);
            cn2.setLocationRelativeTo(null);
            cn2.setVisible(true);
        }
        else if(vidas == 2)
        {
            etq_co2.setVisible(false);
        }
        else if(vidas == 1)
        {
            etq_co1.setVisible(false);
        }
        else if (vidas == 0)
        {
            etq_co.setVisible(false);
            h1.stop();
            h1 = null;
            detenerSonido();
            this.setVisible(false);
            this.dispose();
            GameOver go = new GameOver();
            go.setBounds(30,30,315,340);
            go.setLocationRelativeTo(null);
            go.setVisible(true);
           
            
        }
   
    }
    
     public void reinicioHilo()
        {
          
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_barra = new javax.swing.JPanel();
        btn_reiniciar = new javax.swing.JButton();
        btn_pausa = new javax.swing.JButton();
        etq_puntos = new javax.swing.JLabel();
        etq_vidas = new javax.swing.JLabel();
        etq_co = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        etq_co1 = new javax.swing.JLabel();
        etq_co2 = new javax.swing.JLabel();
        chango = new javax.swing.JLabel();
        comida1 = new javax.swing.JLabel();
        etq_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 800, 600));
        setIconImages(null);
        getContentPane().setLayout(null);

        pnl_barra.setBackground(new java.awt.Color(255, 255, 51));
        pnl_barra.setLayout(null);

        btn_reiniciar.setBackground(new java.awt.Color(255, 102, 51));
        btn_reiniciar.setFont(new java.awt.Font("Waltograph UI", 1, 11)); // NOI18N
        btn_reiniciar.setText("Continuar");
        btn_reiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });
        pnl_barra.add(btn_reiniciar);
        btn_reiniciar.setBounds(210, 10, 100, 20);

        btn_pausa.setBackground(new java.awt.Color(255, 102, 51));
        btn_pausa.setFont(new java.awt.Font("Waltograph UI", 1, 11)); // NOI18N
        btn_pausa.setText("Pause");
        btn_pausa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pausaActionPerformed(evt);
            }
        });
        pnl_barra.add(btn_pausa);
        btn_pausa.setBounds(110, 10, 90, 20);

        etq_puntos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        etq_puntos.setForeground(new java.awt.Color(0, 102, 0));
        etq_puntos.setText("Puntos: 0");
        pnl_barra.add(etq_puntos);
        etq_puntos.setBounds(550, 0, 120, 40);

        etq_vidas.setFont(new java.awt.Font("Waltograph UI", 0, 11)); // NOI18N
        etq_vidas.setText("Vidas:");
        etq_vidas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_barra.add(etq_vidas);
        etq_vidas.setBounds(370, 0, 50, 30);

        etq_co.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CO.png"))); // NOI18N
        pnl_barra.add(etq_co);
        etq_co.setBounds(410, 10, 30, 14);

        btn_iniciar.setBackground(new java.awt.Color(255, 102, 51));
        btn_iniciar.setFont(new java.awt.Font("Waltograph UI", 1, 11)); // NOI18N
        btn_iniciar.setText("Iniciar");
        btn_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        pnl_barra.add(btn_iniciar);
        btn_iniciar.setBounds(10, 10, 90, 20);

        etq_co1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CO.png"))); // NOI18N
        pnl_barra.add(etq_co1);
        etq_co1.setBounds(440, 10, 30, 14);

        etq_co2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CO.png"))); // NOI18N
        pnl_barra.add(etq_co2);
        etq_co2.setBounds(470, 10, 30, 14);

        getContentPane().add(pnl_barra);
        pnl_barra.setBounds(0, 30, 690, 40);

        chango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monofW.gif"))); // NOI18N
        getContentPane().add(chango);
        chango.setBounds(270, 500, 140, 150);

        comida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coco.png"))); // NOI18N
        getContentPane().add(comida1);
        comida1.setBounds(70, 100, 80, 76);

        etq_fondo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etq_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/professorRun_test_bg.png"))); // NOI18N
        getContentPane().add(etq_fondo);
        etq_fondo.setBounds(-120, -10, 1260, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pausaActionPerformed
        h1.suspend();
        pauseSonido();
        btn_pausa.setEnabled(false);
        btn_reiniciar.setEnabled(true);
    }//GEN-LAST:event_btn_pausaActionPerformed

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        h1.resume();
        chango.requestFocus();
        chango.addKeyListener(this);
        reanudarSonido();
        btn_pausa.setEnabled(true);
        btn_reiniciar.setEnabled(false);
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        iniciar();
        iniciarSonido();
    }//GEN-LAST:event_btn_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_pausa;
    private javax.swing.JButton btn_reiniciar;
    public javax.swing.JLabel chango;
    private javax.swing.JLabel comida1;
    private javax.swing.JLabel etq_co;
    private javax.swing.JLabel etq_co1;
    private javax.swing.JLabel etq_co2;
    private javax.swing.JLabel etq_fondo;
    public javax.swing.JLabel etq_puntos;
    private javax.swing.JLabel etq_vidas;
    private javax.swing.JPanel pnl_barra;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        
        
        
        if(e.getKeyChar() == 'a'&&((int)chango.getLocation().getX())>0  || e.getKeyCode() == KeyEvent.VK_LEFT&&((int)chango.getLocation().getX())>0)
        {
            int actualX = (int)chango.getLocation().getX();
            int actualY = (int)chango.getLocation().getY();
            actualX = actualX-10;
            chango.setLocation(actualX, actualY);
            System.out.println(" X : "  + actualX);
            
            if(!h1.isAlive())
            {
                h1.stop();
                h1 = null;
                iniciar();
            }
            
        }
        
        if(e.getKeyChar() == 'd' &&((int)chango.getLocation().getX())<540 || e.getKeyCode() == KeyEvent.VK_RIGHT&&((int)chango.getLocation().getX())<540)
        {
            int actualX = (int)chango.getLocation().getX();
            int actualY = (int)chango.getLocation().getY();
            actualX = actualX+10;
            chango.setLocation(actualX, actualY);
            System.out.println(" X : "  + actualX);
            
            if(!h1.isAlive())
            {
                h1.stop();
                h1 = null;
                iniciar();
                
            }
            
        }
        
        if(e.getKeyChar() == 'x' )
        {
            
            int salir = JOptionPane.showConfirmDialog(null, "Realmente desea salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(salir ==JOptionPane.YES_NO_OPTION )
            {
                h1.stop();
                h1 = null;
                detenerSonido();
                this.dispose();
                menu j = new menu();
                j.setBounds(30,30,560,400);
                j.setLocationRelativeTo(null);
                j.setVisible(true);
  
            }
            else
            {
                
            }
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
