/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catching;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javazoom.jlgui.basicplayer.BasicPlayer;
import javazoom.jlgui.basicplayer.BasicPlayerException;

/**
 *
 * @author Dulce
 */
public class Nivel2 extends javax.swing.JFrame implements KeyListener{ 

    /**
     * Creates new form Nivel2
     */
    
    HiloComidaN2 h2;
    private Random i = new Random();
    private int im =  (int)(i.nextDouble() * 8 + 1);
    public static int puntos2 = 0;
    public static int vidas2 = 3;
    BasicPlayer sonido;
    String archivo = "C:\\Users\\Dulce\\Documents\\NetBeansProjects\\Catching\\src\\sonido\\nivelmaster2.mp3";
    
    public Nivel2() {
         setTitle("NIVEL 2");
          Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/manzana.png"));
        setIconImage(icon);
        initComponents();
        comida1.setVisible(false);
        btn_pausa.setEnabled(false);
        btn_reiniciar.setEnabled(false);
    }
    
    public void iniciarTeclas()
    {
        imgrandom();
        comida1.setVisible(true);
        chango.requestFocus();
        chango.addKeyListener(this);
        h2 = new HiloComidaN2(comida1, chango, etq_puntos, etq_vidas);
        h2.start();
        
    }
    
    public void iniciarSonido()
    {
        try
        {
            sonido = new BasicPlayer();
            sonido.open(new File(archivo));
            sonido.play();
        }
        catch(BasicPlayerException ex)
        {
            System.out.println("Error iniciar sonido" + ex);
        }
    }
    
    public void detenerSonido()
    {
        try
        {
            sonido.open(new File(archivo));
            sonido.stop();
            
        }
        catch(BasicPlayerException ex)
        {
            
        }
    }
    
    public void pauseSonido()
    {
        try {
            sonido.pause();
        } catch (BasicPlayerException ex) {
            System.out.println("Error al pausar sonido" + ex);
        }
    }
    
    public void reanudarSonido()
    {
        try {
            sonido.resume();
        } catch (BasicPlayerException ex) {
            System.out.println("Error al reaundar sonido" + ex);
        }
    }
    
    public void imgrandom()
    {
        
        if(im == 1 || im == 5)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/coco.png")).getImage()));
        }
        else if(im == 2 || im == 6)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/platano.png")).getImage()));
        }
        if(im == 3 || im == 7)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/manzana.png")).getImage()));
        }
        if(im == 4 || im == 8)
        {
            comida1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/img/pera.png")).getImage()));
        }
        
    }
    
    public void iniciar()
    {
        iniciarTeclas();
        btn_pausa.setEnabled(true);
        btn_iniciar.setEnabled(false);
        
        if(puntos2 == 3)
        {
            
            h2.stop();
            h2 = null;
            puntos2 = 0;
            detenerSonido();
            this.setVisible(true);
            this.dispose();
            CambioNivel3 cn3 = new CambioNivel3();
            cn3.setBounds(30,30,400,335);//setBounds(10, 10, 600,500);
            cn3.setLocationRelativeTo(null);
            cn3.setVisible(true);
        }
        else if(vidas2 == 2)
        {
            etq_co2.setVisible(false);
        }
        else if(vidas2 == 1)
        {
            etq_co1.setVisible(false);
        }
        else if (vidas2 == 0)
        {
            etq_co.setVisible(false);
            h2.stop();
            h2 = null;
            detenerSonido();
            this.setVisible(false);
            this.dispose();
            GameOver go = new GameOver();
            go.setBounds(30,30,315,340);
            go.setLocationRelativeTo(null);
            go.setVisible(true);
            
        }
    }
    
    public void reinicioHilo()
        {
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_barra2 = new javax.swing.JPanel();
        btn_reiniciar = new javax.swing.JButton();
        btn_pausa = new javax.swing.JButton();
        etq_vidas = new javax.swing.JLabel();
        etq_co1 = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        etq_co2 = new javax.swing.JLabel();
        etq_co = new javax.swing.JLabel();
        etq_puntos = new javax.swing.JLabel();
        chango = new javax.swing.JLabel();
        comida1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnl_barra2.setBackground(new java.awt.Color(102, 255, 51));
        pnl_barra2.setLayout(null);

        btn_reiniciar.setBackground(new java.awt.Color(255, 255, 51));
        btn_reiniciar.setFont(new java.awt.Font("Waltograph UI", 1, 11)); // NOI18N
        btn_reiniciar.setText("Continuar");
        btn_reiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });
        pnl_barra2.add(btn_reiniciar);
        btn_reiniciar.setBounds(210, 10, 100, 20);

        btn_pausa.setBackground(new java.awt.Color(255, 255, 51));
        btn_pausa.setFont(new java.awt.Font("Waltograph UI", 1, 11)); // NOI18N
        btn_pausa.setText("Pause");
        btn_pausa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pausaActionPerformed(evt);
            }
        });
        pnl_barra2.add(btn_pausa);
        btn_pausa.setBounds(110, 10, 90, 20);

        etq_vidas.setFont(new java.awt.Font("Waltograph UI", 0, 11)); // NOI18N
        etq_vidas.setText("Vidas:");
        etq_vidas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_barra2.add(etq_vidas);
        etq_vidas.setBounds(350, 0, 60, 30);

        etq_co1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CO.png"))); // NOI18N
        pnl_barra2.add(etq_co1);
        etq_co1.setBounds(430, 10, 34, 14);

        btn_iniciar.setBackground(new java.awt.Color(255, 255, 51));
        btn_iniciar.setFont(new java.awt.Font("Waltograph UI", 1, 11)); // NOI18N
        btn_iniciar.setText("Iniciar");
        btn_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        pnl_barra2.add(btn_iniciar);
        btn_iniciar.setBounds(10, 10, 90, 20);

        etq_co2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CO.png"))); // NOI18N
        pnl_barra2.add(etq_co2);
        etq_co2.setBounds(460, 10, 34, 14);

        etq_co.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CO.png"))); // NOI18N
        pnl_barra2.add(etq_co);
        etq_co.setBounds(400, 10, 34, 14);

        etq_puntos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        etq_puntos.setForeground(new java.awt.Color(255, 0, 0));
        etq_puntos.setText("Puntos: 0");
        pnl_barra2.add(etq_puntos);
        etq_puntos.setBounds(550, 0, 120, 40);

        getContentPane().add(pnl_barra2);
        pnl_barra2.setBounds(0, 30, 690, 40);

        chango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FFGF.gif"))); // NOI18N
        getContentPane().add(chango);
        chango.setBounds(270, 500, 140, 150);

        comida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pera.png"))); // NOI18N
        getContentPane().add(comida1);
        comida1.setBounds(260, 130, 80, 70);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva-01.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-110, 0, 1260, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        h2.resume();
        chango.requestFocus();
        chango.addKeyListener(this);
        btn_pausa.setEnabled(true);
        btn_reiniciar.setEnabled(false);
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    private void btn_pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pausaActionPerformed
        h2.suspend();
        btn_pausa.setEnabled(false);
        btn_reiniciar.setEnabled(true);
    }//GEN-LAST:event_btn_pausaActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        iniciar();
       iniciarSonido();
    }//GEN-LAST:event_btn_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_pausa;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JLabel chango;
    private javax.swing.JLabel comida1;
    private javax.swing.JLabel etq_co;
    private javax.swing.JLabel etq_co1;
    private javax.swing.JLabel etq_co2;
    public javax.swing.JLabel etq_puntos;
    private javax.swing.JLabel etq_vidas;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel pnl_barra2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
      public void keyPressed(KeyEvent e) {
        if(e.getKeyChar() == 'a' &&((int)chango.getLocation().getX())>0 || e.getKeyCode() == KeyEvent.VK_LEFT&&((int)chango.getLocation().getX())>0)
        {
            int actualX = (int)chango.getLocation().getX();
            int actualY = (int)chango.getLocation().getY();
            actualX = actualX-10;
            chango.setLocation(actualX, actualY);
            System.out.println(" X : "  + actualX);
            if(!h2.isAlive())
            {
                h2.stop();
                h2 = null;
                iniciar();
            }
        }
        
        if(e.getKeyChar() == 'd'&&((int)chango.getLocation().getX())<540 || e.getKeyCode() == KeyEvent.VK_RIGHT&&((int)chango.getLocation().getX())<540)
        {
            int actualX = (int)chango.getLocation().getX();
            int actualY = (int)chango.getLocation().getY();
            actualX = actualX+10;
            chango.setLocation(actualX, actualY);
            System.out.println(" X : "  + actualX);
            if(!h2.isAlive())
            {
                h2.stop();
                h2 = null;
                iniciar();
            }
        }
        
        if(e.getKeyChar() == 'x' )
        {
            
            int salir = JOptionPane.showConfirmDialog(null, "Realmente desea salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(salir ==JOptionPane.YES_NO_OPTION )
            {
                h2.stop();
                h2 = null;
                detenerSonido();
                this.dispose();
                menu j = new menu();
                j.setBounds(30,30,560,400);
                j.setLocationRelativeTo(null);
                j.setVisible(true);
  
            }
            else
            {
                
            }
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
